name: Deploy to InfinityFree

on:
  push:
    branches:
      - main  # Adjust if you're using a different branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Deploy to InfinityFree
        uses: lukaszlach/ftp-action@v1
        with:
          host: ftp://ftpupload.net
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          localDir: /htdocs
